version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgre_base:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: jeniks/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static_backend/
      - media_value:/media/
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - ./.env

  frontend:
    image: jeniks/foodgram_frontend:latest
    volumes:
      - ./:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
volumes:
  postgre_base:
  static_value:
  media_value: